## DATA ANALAYSIS--->


**PANDAS-->PANEL+DATA**

**used to manipulate the data,clean data,organige and preprocess the data**

**pandas data structure-->Series,DataFrame**

**Pandas Series-->one dimensional labelled array**

In [ ]:
import pandas as pd
lst=[12,23,56,87,90,34]
lst

[12, 23, 56, 87, 90, 34]

In [ ]:
x=pd.Series(lst )
type(x)

pandas.core.series.Series

In [ ]:
## list to series
subject=["python","ml","ai"]
marks=[45,98,68]
gpa=[4.5,9.8,6.8]

pd.Series([subject,marks,gpa])

0    [python, ml, ai]
1        [45, 98, 68]
2     [4.5, 9.8, 6.8]
dtype: object

In [ ]:
import seaborn as sns
resto=sns.load_dataset("tips")
resto.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
type(resto)

pandas.core.frame.DataFrame

In [ ]:
z

NameError: name 'z' is not defined

In [ ]:
type(resto.day)

pandas.core.series.Series

In [ ]:
## no of rows and columns
resto.shape

(244, 7)

In [ ]:
# check data type of each column
resto.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
## check duplicates data
resto.duplicated().sum()

np.int64(1)

In [ ]:
resto[resto.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [ ]:
resto.drop_duplicates(inplace=True)

In [ ]:
resto.duplicated().sum()

np.int64(0)

In [ ]:
subject=["python","ml","ai"]
marks=[45,98,68]
gpa=(4.5,9.8,6.8)

pd.DataFrame([subject,marks,gpa],index=["subject","marks","gpa"]).T

  subject marks  gpa
0  python    45  4.5
1      ml    98  9.8
2      ai    68  6.8

In [ ]:
## data info
resto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  243 non-null    float64
 1   tip         243 non-null    float64
 2   sex         243 non-null    category
 3   smoker      243 non-null    category
 4   day         243 non-null    category
 5   time        243 non-null    category
 6   size        243 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 9.1 KB

In [ ]:
## statistical information
resto.describe()

       total_bill         tip        size
count  243.000000  243.000000  243.000000
mean    19.813868    3.002387    2.572016
std      8.910071    1.385002    0.952356
min      3.070000    1.000000    1.000000
25%     13.380000    2.000000    2.000000
50%     17.810000    2.920000    2.000000
75%     24.175000    3.575000    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
resto.describe(include="category")

         sex smoker  day    time
count    243    243  243     243
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

## indexing and slicing

In [ ]:
resto.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
resto[10:15]

    total_bill   tip     sex smoker  day    time  size
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

In [ ]:
import numpy as np
array=np.arange(10,30).reshape(5,4)
array

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [ ]:
array[2,1:3]

array([19, 20])

In [ ]:
resto[10:15,0:2]

InvalidIndexError: (slice(10, 15, None), slice(0, 2, None))

In [ ]:
resto.iloc[10:15,[0,2,4]]

    total_bill     sex  day
10       10.27    Male  Sun
11       35.26  Female  Sun
12       15.42    Male  Sun
13       18.43    Male  Sun
14       14.83  Female  Sun

In [ ]:
## loc
resto.loc[10:15,["total_bill","sex","time"]]

    total_bill     sex    time
10       10.27    Male  Dinner
11       35.26  Female  Dinner
12       15.42    Male  Dinner
13       18.43    Male  Dinner
14       14.83  Female  Dinner
15       21.58    Male  Dinner

In [ ]:
## add new data
resto.tail(1)

     total_bill  tip     sex smoker   day    time  size
243       18.78  3.0  Female     No  Thur  Dinner     2

In [ ]:
resto.loc[244]=[20.54,2.0,"Male","Yes","Sat","Lunch",1]
resto.tail(2)

     total_bill  tip     sex smoker   day    time  size
243       18.78  3.0  Female     No  Thur  Dinner     2
244       20.54  2.0    Male    Yes   Sat   Lunch     1

In [ ]:
resto["bill_per_size"]=resto.total_bill/resto.size*1000
resto.head()

   total_bill   tip     sex smoker  day    time  size  bill_per_size
0       16.99  1.01  Female     No  Sun  Dinner     2       8.703893
1       10.34  1.66    Male     No  Sun  Dinner     3       5.297131
2       21.01  3.50    Male     No  Sun  Dinner     3      10.763320
3       23.68  3.31    Male     No  Sun  Dinner     2      12.131148
4       24.59  3.61  Female     No  Sun  Dinner     4      12.597336

In [ ]:
## data sorting
resto.sort_values(by="total_bill",ascending=False,ignore_index=True)

     total_bill    tip     sex smoker   day    time  size  bill_per_size
0         50.81  10.00    Male    Yes   Sat  Dinner     3      26.029713
1         48.33   9.00    Male     No   Sat  Dinner     4      24.759221
2         48.27   6.73    Male     No   Sat  Dinner     4      24.728484
3         48.17   5.00    Male     No   Sun  Dinner     6      24.677254
4         45.35   3.50    Male    Yes   Sun  Dinner     3      23.232582
..          ...    ...     ...    ...   ...     ...   ...            ...
239        7.51   2.00    Male     No  Thur   Lunch     2       3.847336
240        7.25   1.00  Female     No   Sat  Dinner     1       3.714139
241        7.25   5.15    Male    Yes   Sun  Dinner     2       3.714139
242        5.75   1.00  Female    Yes   Fri  Dinner     2       2.945697
243        3.07   1.00  Female    Yes   Sat  Dinner     1       1.572746

[244 rows x 8 columns]

In [ ]:
## count number of words in text
text="python is fun to learn"
text

'python is fun to learn'

In [ ]:
list(map(len,text.split()))

[6, 2, 3, 2, 5]

In [ ]:
ser1=pd.Series([12,13,14,15,16])
ser2=pd.Series([21,22,23,24,25])
pd.concat([ser1,ser2],keys=["ser1","ser2"],axis=1)

   ser1  ser2
0    12    21
1    13    22
2    14    23
3    15    24
4    16    25

In [ ]:
# create a DataFrame from a dictionary
import pandas as pd
df_prof_info_A = pd.DataFrame({
   'Emp_ID': [1001,1002,1003,1004,1005],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Stephan'],
   'Gender':['M', 'F', 'M', 'F', 'M'],
   'Company':['Apple','Walmart','Intel','Cummins','Ford'],
   'Salary':[67000,90000,87000,69000,78000]},
   index=[101,102,103,104,105])

# print the DataFrame
print("The first DataFrame is : \n",df_prof_info_A)

print("\n\n")

# create a DataFrame from a dictionary
df_prof_info_B = pd.DataFrame({
    'Emp_ID': [1006,1007,1008,1009,1010,1011],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty','James'],
    'Gender':['M', 'M', 'M', 'F', 'F','M'],
   'Company':['Cognizant','Apple','Intel','Cummins','Walmart','Intel'],
   'Salary':[89000,80000,79000,97000,88000,89000]},
   index=[106,107,108,109,110,111])

# print the DataFrame
print("The second DataFrame is : \n",df_prof_info_B)

print("\n\n")

# create a DataFrame from a dictionary
df_pers_info_A = pd.DataFrame({
     'Emp_ID': [1001,1002,1003,1004,1005],
   'Hometown': ['New York', 'London', 'San Francisco', 'Seattle', 'Madrid'],
     'Gender':['M', 'F', 'M', 'F', 'M'],
    'Marital':['Married','Divorsed','Single','Married','Single'],
   'Dependents':[1,1,3,2,1]},
   index=[101,102,103,104,105])

# print the DataFrame
print("The third DataFrame is : \n",df_pers_info_A)

print("\n\n")

# create a DataFrame from a dictionary
df_pers_info_B = pd.DataFrame({
     'Emp_ID': [1006,1007,1009,1010,1011,1012],
   'Hometown': ['Paris', 'Boston', 'San Francisco', 'Seattle', 'London','London'],
    'Marital':['Married','Divorsed','Single','Married','Single','Single'],
   'Dependents':[1,1,3,2,1,2]},
   index=[106,107,108,109,110,111])

# print the DataFrame
print("The fourth DataFrame is : \n",df_pers_info_B)

The first DataFrame is :
      Emp_ID     Name Gender  Company  Salary
101    1001     Alex      M    Apple   67000
102    1002      Amy      F  Walmart   90000
103    1003    Allen      M    Intel   87000
104    1004    Alice      F  Cummins   69000
105    1005  Stephan      M     Ford   78000



The second DataFrame is :
      Emp_ID   Name Gender    Company  Salary
106    1006  Billy      M  Cognizant   89000
107    1007  Brian      M      Apple   80000
108    1008   Bran      M      Intel   79000
109    1009  Bryce      F    Cummins   97000
110    1010  Betty      F    Walmart   88000
111    1011  James      M      Intel   89000



The third DataFrame is :
      Emp_ID       Hometown Gender   Marital  Dependents
101    1001       New York      M   Married           1
102    1002         London      F  Divorsed           1
103    1003  San Francisco      M    Single           3
104    1004        Seattle      F   Married           2
105    1005         Madrid      M    Single           1



The fourth DataFrame is :
      Emp_ID       Hometown   Marital  Dependents
106    1006          Paris   Married           1
107    1007         Boston  Divorsed           1
108    1009  San Francisco    Single           3
109    1010        Seattle   Married           2
110    1011         London    Single           1
111    1012         London    Single           2

In [ ]:
pd.concat([df_prof_info_A,df_prof_info_B],axis=0)

     Emp_ID     Name Gender    Company  Salary
101    1001     Alex      M      Apple   67000
102    1002      Amy      F    Walmart   90000
103    1003    Allen      M      Intel   87000
104    1004    Alice      F    Cummins   69000
105    1005  Stephan      M       Ford   78000
106    1006    Billy      M  Cognizant   89000
107    1007    Brian      M      Apple   80000
108    1008     Bran      M      Intel   79000
109    1009    Bryce      F    Cummins   97000
110    1010    Betty      F    Walmart   88000
111    1011    James      M      Intel   89000

In [ ]:
pd.concat([df_prof_info_A,df_pers_info_A],axis=1).T.drop_duplicates().T

    Emp_ID     Name Gender  Company Salary       Hometown   Marital Dependents
101   1001     Alex      M    Apple  67000       New York   Married          1
102   1002      Amy      F  Walmart  90000         London  Divorsed          1
103   1003    Allen      M    Intel  87000  San Francisco    Single          3
104   1004    Alice      F  Cummins  69000        Seattle   Married          2
105   1005  Stephan      M     Ford  78000         Madrid    Single          1

In [ ]:
## Append-->
df_prof_info_A._append(df_prof_info_B)

     Emp_ID     Name Gender    Company  Salary
101    1001     Alex      M      Apple   67000
102    1002      Amy      F    Walmart   90000
103    1003    Allen      M      Intel   87000
104    1004    Alice      F    Cummins   69000
105    1005  Stephan      M       Ford   78000
106    1006    Billy      M  Cognizant   89000
107    1007    Brian      M      Apple   80000
108    1008     Bran      M      Intel   79000
109    1009    Bryce      F    Cummins   97000
110    1010    Betty      F    Walmart   88000
111    1011    James      M      Intel   89000

In [ ]:
## merge-->combine two or more table to form single table
pd.merge(df_prof_info_A,df_pers_info_A,on=["Emp_ID","Gender"])

,Emp_ID,Name,Gender,Company,Salary,Hometown,Marital,Dependents
0,1001,Alex,M,Apple,67000,New York,Married,1
1,1002,Amy,F,Walmart,90000,London,Divorsed,1
2,1003,Allen,M,Intel,87000,San Francisco,Single,3
3,1004,Alice,F,Cummins,69000,Seattle,Married,2
4,1005,Stephan,M,Ford,78000,Madrid,Single,1

## PIVOT TABLE

In [ ]:
airline=pd.read_excel("/content/Data_Train.xlsx")
airline.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [ ]:
import numpy as np
pd.pivot_table(airline,"Price","Airline","Total_Stops",fill_value="",)

Total_Stops,1 stop,2 stops,3 stops,4 stops,non-stop
Airline,,,,,
Air Asia,7078.325581,6341.888889,,,4492.331492
Air India,9041.509259,12092.779101,12208.054054,17686.0,5605.326139
GoAir,6884.676471,,,,4726.173913
IndiGo,7104.717528,7507.526316,,,4731.174053
Jet Airways,12512.741223,13387.247467,,,6175.078652
Jet Airways Business,62844.25,49387.5,,,
Multiple carriers,10711.316157,14809.395349,17292.75,,
Multiple carriers Premium economy,11418.846154,,,,
SpiceJet,6750.560811,,,,3805.423881
Trujet,4140.0,,,,
Vistara,9641.148837,,,,6293.954545
Vistara Premium economy,,,,,8962.333333

## crosstab-->its similiar to pivot_table but it only used to createc report based on categorical columns

In [ ]:
data=pd.read_csv("/content/people.csv")
data.head()

   Age  Gender Hometown  Height  Qualification Smoker
0   45    Male   Mumbai     167       Graduate    Yes
1   23  Female   Mumbai     170       Graduate     No
2   27    Male   Mumbai     175  Post-graduate     No
3   34    Male    Delhi     155       Graduate     No
4   43  Female   Mumbai     157  Post-graduate    Yes

In [ ]:
pd.crosstab(data.Gender,data.Smoker,values=data.Age,aggfunc="min",rownames=["gen"],colnames=["smoke"])

smoke   No  Yes
gen
Female  21   43
Male    27   34

In [ ]:
import seaborn as sns
x=sns.load_dataset("tips")
x.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
x.drop(index=[2,4,8],columns=["sex","smoker"],inplace=True)

In [ ]:
x.head()

   total_bill   tip  day    time  size
0       16.99  1.01  Sun  Dinner     2
1       10.34  1.66  Sun  Dinner     3
3       23.68  3.31  Sun  Dinner     2
5       25.29  4.71  Sun  Dinner     4
6        8.77  2.00  Sun  Dinner     2

In [ ]:
**syntax**

lambda infinite_arguments:expression

## MAP AND REPLACE

In [ ]:
words=["python","ml","artificial inelligence"]
list(map(lambda  x:x.capitalize(),words))

['Python', 'Ml', 'Artificial inelligence']

In [ ]:
import pandas as pd
df_demography = pd.DataFrame({'Country':['China','India','USA','Indonesia','Brazil'],
                  'Population':[1403500365,1324171354,322179605,261115456,207652865]})

# print the DataFrame
df_demography

     Country  Population
0      China  1403500365
1      India  1324171354
2        USA   322179605
3  Indonesia   261115456
4     Brazil   207652865

In [ ]:
capital={
    "China":"Beizing",
    "australlia":"canbera",
    "japan":"tokyo",
    "India":"Delhi",
    "USA":"NWC",
    "Indonesia":"jakarta",
    "Brazil":"Brasillia"
}

In [ ]:
df_demography["capital"]=df_demography.Country.map(capital)
df_demography

     Country  Population    capital
0      China  1403500365    Beizing
1      India  1324171354      Delhi
2        USA   322179605        NWC
3  Indonesia   261115456    jakarta
4     Brazil   207652865  Brasillia

In [ ]:
x

     total_bill   tip   day    time  size
0         16.99  1.01   Sun  Dinner     2
1         10.34  1.66   Sun  Dinner     3
3         23.68  3.31   Sun  Dinner     2
5         25.29  4.71   Sun  Dinner     4
6          8.77  2.00   Sun  Dinner     2
..          ...   ...   ...     ...   ...
239       29.03  5.92   Sat  Dinner     3
240       27.18  2.00   Sat  Dinner     2
241       22.67  2.00   Sat  Dinner     2
242       17.82  1.75   Sat  Dinner     2
243       18.78  3.00  Thur  Dinner     2

[241 rows x 5 columns]

In [ ]:
x.day.value_counts()

day
Sat     87
Sun     73
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
x.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
x.day=x.day.map({"Thur":0,"Fri":1,"Sat":2,"Sun":3})
x.head()

   total_bill   tip day    time  size
0       16.99  1.01   3  Dinner     2
1       10.34  1.66   3  Dinner     3
3       23.68  3.31   3  Dinner     2
5       25.29  4.71   3  Dinner     4
6        8.77  2.00   3  Dinner     2

In [ ]:
## replace
x.time=x.time.replace({"Dinner":np.nan})
x

/tmp/ipykernel_570/389716020.py:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  x.time=x.time.replace({"Dinner":np.nan})

     total_bill   tip day time  size
0         16.99  1.01   3  NaN     2
1         10.34  1.66   3  NaN     3
3         23.68  3.31   3  NaN     2
5         25.29  4.71   3  NaN     4
6          8.77  2.00   3  NaN     2
..          ...   ...  ..  ...   ...
239       29.03  5.92   2  NaN     3
240       27.18  2.00   2  NaN     2
241       22.67  2.00   2  NaN     2
242       17.82  1.75   2  NaN     2
243       18.78  3.00   0  NaN     2

[241 rows x 5 columns]

In [ ]:
## Group by-->